version: "3"
services:
  #app:
  #  container_name: app
  #  restart: always
  #  build: .
  #  environment:
  #    - PORT=3000
  #  ports:
  #    - "3000:3000"
  #  links:
  #    - mongo
  #  depends_on:
  #    - mongo
  #    - mysql
  #  networks:
  #    - core_service_network
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - core_service_network
  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - core_service_network
networks:
  core_service_network:
    driver: bridge
volumes:
  mysql_data:
  mongo_data:
