version: "3"
services:
  #app:
  #  container_name: app
  #  restart: always
  #  build: .
  #  environment:
  #    - PORT=3000
  #  ports:
  #    - "3000:3000"
  #  links:
  #    - mongo
  #mongo:
  #  container_name: mongo
  #  image: mongo
  #  ports:
  #    - "27017:27017"
  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
volumes:
  mysql_db_data_container: